# This rule is not used by the project nginx-static-page itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to static.cafeco.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginx-static-page
    app.kubernetes.io/managed-by: kustomize
  name: nginxstaticpage-viewer-role
rules:
- apiGroups:
  - static.cafeco.io
  resources:
  - nginxstaticpages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - static.cafeco.io
  resources:
  - nginxstaticpages/status
  verbs:
  - get
